export enum todoTypes {
  FETCH_TODO_REQUEST = "FETCH_TODO_REQUEST",
  FETCH_TODO_SUCCESS = "FETCH_TODO_SUCCESS",
  FETCH_TODO_FAILURE = "FETCH_TODO_FAILURE",

  DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST",
  DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS",
  DELETE_TODO_FAILURE = "DELETE_TODO_FAILURE"
}